name: CI/CD Pipeline

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Deploy to Prod
        if: github.event_name == 'release' && github.event.release.target_commitish == 'main'
        id: deploy_prod
        run: |
          npx sls deploy --verbose -s prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'
        id: deploy_stg
        run: |
          npx sls deploy --verbose -s stg
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run tests
        if: steps.deploy_stg.conclusion == 'success'
        run: pnpm test
